Release 3.0.0
eea/volto-slate pull request #142
Opened 2021-09-01 20:42 UTC by avoinea

2021-09-02 06:39 UTC, tiberiuichim submitted a review, later dismissed

2021-09-02 11:43 UTC, razvanMiu submitted a review, later dismissed

2021-09-02 11:49 UTC, nileshgulia1 approved these changes

2021-09-03 07:10 UTC, tiberiuichim requested changes
Without installTable the tables are no longer pasted as tables, they just become paragraphs. Only the table button should be made optional, not the entire table plugin.

2021-09-05 17:51 UTC, tiberiuichim commented
@avoinea Another issue in this branch: no longer split in multi-blocks.

2021-09-07 17:26 UTC, avoinea commented
Close until we fix all the remaining issues

2021-09-07 17:26 UTC, closed without merging